import os

NAME = "Oblivius"
APP_NAME = "Ripper"
VERSION = "V2.0"

CONFIGURATION_FILE = "config.conf"
LOG_COUNT = 10

RESOLUTION_X = 420
RESOLUTION_Y = 470

##### DEFAULTS #####
DOWNLOAD_PATH = os.path.expanduser('~')
DEBUG_LEVEL = 10  # 10:DEBUG 20:INFO 30:WARN 40:ERROR 50:CRITICAL
DOWNLOAD_CONTAINER = "MP4"
VIDEO_CONTAINERS = "AV1", "FLV", "MKV", "M4V", "MOV", "MP4", "WebM"
AUDIO_CONTAINERS = "ALAC", "FLAC", "M4A", "MP3", "OGG", "WAV", "WebM"
